name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check format
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && sh ./tools/check_format.sh

  test_horaedb_common:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects horaedb-common test
            || mvn --projects horaedb-common test
            || mvn --projects horaedb-common test)

  test_horaedb_grpc:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects horaedb-grpc test
            || mvn --projects horaedb-grpc test
            || mvn --projects horaedb-grpc test)

  test_horaedb_protocol:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects horaedb-protocol test
            || mvn --projects horaedb-protocol test
            || mvn --projects horaedb-protocol test)

  test_horaedb_sql:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects horaedb-sql test
            || mvn --projects horaedb-sql test
            || mvn --projects horaedb-sql test)

  test_horaedb_javacc:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects horaedb-sql-javacc test
            || mvn --projects horaedb-sql-javacc test
            || mvn --projects horaedb-sql-javacc test)